#spring.application.name=ecom
#server.port= 8089
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
server:
  port: 8089

spring:
  application:
    name: ecom
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true


