#spring.application.name=ecom
#server.port= 8089
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
# management.endpoints.web.exposure.include = *
server:
  port: 8089

spring:
  application:
    name: ecom
  datasource:
    url: jdbc:postgresql://localhost:5432/ecomdb
    username: embarkx
    password: embarkx
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  #h2:
  #  console:
  #    enabled: true
  #    settings:
  #      web-allow-others: true
  #datasource:
  #  url: jdbc:h2:mem:test
  #jpa:
  #  hibernate:
  #    ddl-auto: create
  #  show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true


info:
  app:
    name: MyApp
    description: App build by us
    version: 1.0.0



